//areas_store
export const GET_AREAS = "GET_AREAS";
export const GET_AREAS_SUCCESS = "GET_AREAS_SUCCESS";
export const GET_AREAS_ERROR = "GET_AREAS_ERROR";

export const GET_AREA = "GET_AREA";
export const GET_AREA_SUCCESS = "GET_AREA_SUCCESS";
export const GET_AREA_ERROR = "GET_AREA_ERROR";

export const ADD_AREA = "ADD_AREA";
export const ADD_AREA_SUCCESS = "ADD_AREA_SUCCESS";
export const ADD_AREA_ERROR = "ADD_AREA_ERROR";

export const DELETE_AREA = "DELETE_AREA";
export const DELETE_AREA_SUCCESS = "DELETE_AREA_SUCCES";
export const DELETE_AREA_ERROR = "DELETE_AREA_ERROR";

export const UPDATE_AREA = "UPDATE_AREA";
export const UPDATE_AREA_SUCCESS = "UPDATE_AREA_SUCCES";
export const UPDATE_AREA_ERROR = "UPDATE_AREA_ERROR";