//authentication_store
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESSS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGGIN_ERROR";

export const LOGOUT = "LOGOUT";

//users_store
export const GET_USERS = "GET_USERS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const GET_USERS_ERROR = "GET_USERS_ERROR";

export const ADD_USER = "ADD_USER";
export const ADD_USER_SUCCESS = "ADD_USER_SUCCESS";
export const ADD_USER_ERROR = "ADD_USER_ERROR";

//researches_store
export const GET_RESEARCHES = "GET_RESEARCHES";
export const GET_RESEARCHES_SUCCESS = "GET_RESEARCHES_SUCCESS";
export const GET_RESEARCHES_ERROR = "GET_RESEARCHES_ERROR";

export const ADD_RESEARCH = "ADD_RESEARCH";
export const ADD_RESEARCH_SUCCESS = "ADD_RESEARCH_SUCCESS";
export const ADD_RESEARCH_ERROR = "ADD_RESEARCH_ERROR";

export const GET_RESEARCH = "GET_RESEARCH";
export const GET_RESEARCH_SUCCESS = "GET_RESEARCH_SUCCESS";
export const GET_RESEARCH_ERROR = "GET_RESEARCH_ERROR";

//areas_store
export const GET_AREAS = "GET_AREAS";
export const GET_AREAS_SUCCESS = "GET_AREAS_SUCCESS";
export const GET_AREAS_ERROR = "GET_AREAS_ERROR";

export const GET_AREA = "GET_AREA";
export const GET_AREA_SUCCESS = "GET_AREA_SUCCESS";
export const GET_AREA_ERROR = "GET_AREA_ERROR";

export const ADD_AREA = "ADD_AREA";
export const ADD_AREA_SUCCESS = "ADD_AREA_SUCCESS";
export const ADD_AREA_ERROR = "ADD_AREA_ERROR";

export const DELETE_AREA = "DELETE_AREA";
export const DELETE_AREA_SUCCESS = "DELETE_AREA_SUCCES";
export const DELETE_AREA_ERROR = "DELETE_AREA_ERROR";

export const UPDATE_AREA = "UPDATE_AREA";
export const UPDATE_AREA_SUCCESS = "UPDATE_AREA_SUCCES";
export const UPDATE_AREA_ERROR = "UPDATE_AREA_ERROR";

//models_store
export const GET_MODELS = "GET_MODELS";
export const GET_MODELS_SUCCESS = "GET_MODELS_SUCCESS";
export const GET_MODELS_ERROR = "GET_MODELS_ERROR";

export const GET_MODEL = "GET_MODEL";
export const GET_MODEL_SUCCESS = "GET_MODEL_SUCCESS";
export const GET_MODEL_ERROR = "GET_MODEL_ERROR";

export const ADD_MODEL = "ADD_MODEL";
export const ADD_MODEL_SUCCESS = "ADD_MODEL_SUCCESS";
export const ADD_MODEL_ERROR = "ADD_MODEL_ERROR";

export const DELETE_MODEL = "DELETE_MODEL";
export const DELETE_MODEL_SUCCESS = "DELETE_MODEL_SUCCES";
export const DELETE_MODEL_ERROR = "DELETE_MODEL_ERROR";

export const UPDATE_MODEL = "UPDATE_MODEL";
export const UPDATE_MODEL_SUCCESS = "UPDATE_MODEL_SUCCES";
export const UPDATE_MODEL_ERROR = "UPDATE_MODEL_ERROR";