#!/bin/bash

echo "Creating users..."
echo "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT!"

echo "$MONGO_INITDB_DATABASE"
echo "$MONGO_INITDB_ROOT_USERNAME"
echo "$MONGO_INITDB_ROOT_PASSWORD"

# mongo -- "$MONGO_INITDB_DATABASE" <<EOF
#     db.createUser({
#         user: "$MONGO_INITDB_ROOT_USERNAME",
#         pwd: "$MONGO_INITDB_ROOT_PASSWORD",
#         roles: [{
#             role: "readWrite",
#             db: "$MONGO_INITDB_DATABASE"
#         }]
#     });

#     db.users.insertOne({
#         fullname: "researcher",
#         email: "researcher@flowerpower.com",
#         role: "researcher",
#         password: "$INITIAL_PASSWORD"
#     });
# EOF

echo "done?"
echo "TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT!"
