export const SOCKET_CONNECT = "SOCKET_CONNECT";
export const SOCKET_CONNECT_SUCCESS = "SOCKET_CONNECT_SUCCESS";
export const SOCKET_CONNECT_ERROR = "SOCKET_CONNECT_ERROR";

export const SOCKET_DISCONNECT = "SOCKET_DISCONNECT";

export const SOCKET_SEND_MESSAGE = "SOCKET_SEND_MESSAGE";

export const SOCKET_ON_SEND_MESSAGE = "SOCKET_ON_SEND_MESSAGE";