//WEBSOCKET_CHANNELS
export const DETECT_IMAGES = "DETECT_IMAGES";
export const SPLIT_IMAGES = "SPLIT_IMAGES";
export const FLY_AND_LAND = "FLY_AND_LAND"

//IPC_CHANNELS
export const FILESYSTEM = "FILESYSTEM";

//IPC_ACTIONS
export const SELECT_FOLDER = "SELECT_FOLDER";