//WEBSOCKET_CHANNELS
export const DETECT_IMAGES = "DETECT_IMAGES";
export const SPLIT_IMAGES = "SPLIT_IMAGES";
export const FLY_AND_LAND = "FLY_AND_LAND"

//IPC_CHANNELS
export const FILESYSTEM = "FILESYSTEM";
export const DOWNLOAD = "DOWNLOAD";

//IPC_ACTIONS
export const IPC_MESSAGES = {
    SELECT_FOLDER: "SELECT_FOLDER",
    GET_IMAGE_FILES_FROM_FOLDER: "GET_IMAGE_FILES_FROM_FOLDER"
}