//WEBSOCKET_CHANNELS
export const SOCKET_CHANNELS = {
    DETECT_IMAGES: "DETECT_IMAGES",
    SPLIT_IMAGES: "SPLIT_IMAGES",
    FLY_AND_LAND: "FLY_AND_LAND",
    DRONE_INIT: "DRONE_INIT",
    DRONE_MESSAGE: "DRONE_MESSAGE",
    DRONE_EMERGENCY_STOP: "DRONE_EMERGENCY_STOP",
    DRONE_STOP: "DRONE_STOP",
}

//IPC_CHANNELS
export const IPC_CHANNELS = {
    FILESYSTEM: "FILESYSTEM",
    DOWNLOAD_WEIGHTS: "DOWNLOAD_WEIGHTS",
    REMOVE_WEIGHT: "REMOVE_WEIGHT",
    GET_WEIGHTS_FROM_FOLDER: "GET_IMAGE_FILES_FROM_FOLDER",
    DATABASE: "DATABASE"
}

//IPC_ACTIONS
export const IPC_MESSAGES = {
    SELECT_FOLDER: "SELECT_FOLDER",
    GET_IMAGE_FILES_FROM_FOLDER: "GET_IMAGE_FILES_FROM_FOLDER",
    COPY_IMAGES_FROM_FOLDER: "COPY_IMAGES_FROM_FOLDER",
    DOWNLOAD_IMAGES_FROM_FOLDER: "DOWNLOAD_IMAGES_FROM_FOLDER",
    SAVE_IN_DB: "SAVE_IN_DB",
    UPDATE_IN_DB: "UPDATE_IN_DB",
    FIND_IN_DB: "FIND_IN_DB",
    COUNT_IN_DB: "COUNT_IN_DB",
    REMOVE_IN_DATABASE: "REMOVE_IN_DATABASE",
    RESET_DATABASE: "RESET_DATABASE"
}

//DATABASE NAMES
export const DB_NAMES = {
    RESEARCHDB: "RESEARCHDB",
    MODELDB: "MODELDB",
    SESSIONSDB: "SESSIONSDB"
}